Consolidated the group member status read funcs into an enum
session-foundation/libsession-util pull request #5
Opened 2024-11-22 04:54 UTC by mpretty-cyro

2024-11-22 05:10 UTC, Bilb requested changes

2024-11-22 05:10 UTC, Bilb commented on include/session/config/groups/members.h
> +    GROUP_MEMBER_STATUS_INVITE_ACCPETED = 4,
typo here ACCPETED

2024-11-22 05:10 UTC, Bilb commented on include/session/config/groups/members.h
> +    GROUP_MEMBER_STATUS_PROMOTION_ACCPETED = 9,
same

2024-11-22 05:47 UTC, mpretty-cyro commented on include/session/config/groups/members.h
> +    GROUP_MEMBER_STATUS_INVITE_ACCPETED = 4,
Fixed

2024-11-22 05:47 UTC, mpretty-cyro commented on include/session/config/groups/members.h
> +    GROUP_MEMBER_STATUS_PROMOTION_ACCPETED = 9,
Fixed

2024-11-25 00:42 UTC, Bilb approved these changes

2024-11-25 01:07 UTC, merged